[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "apscheduler>=3.11.0",
    "fastapi[standard]>=0.115.13",
    "requests>=2.32.4",
    "skyfield>=1.53",
    "sqlalchemy>=2.0.41",
]
